# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='city',
            name='icon',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
