# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_weather', '0004_auto_20180514_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, choices=[('London', 'London'), ('Tokyo', 'Tokyo'), ('New York', 'New York'), ('Liverpool', 'Liverpool'), ('Kyiv', 'Kyiv'), ('Vinnytsia', 'Vinnytsia'), ('Las Vegas', 'Las Vegas'), ('Donetsk', 'Donetsk'), ('Lviv', 'Lviv'), ('Baku', 'Baku'), ('Moscow', 'Moscow'), ('Sevastopol', 'Sevastopol'), ('Paris', 'Paris')], max_length=30),
        ),
    ]
