# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_weather', '0005_auto_20180514_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NewCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('temperature', models.FloatField(default=0)),
                ('description', models.CharField(blank=True, max_length=40)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
